# GitHub Action Workflow for building a pull request commit and validating that the commit builds for all
# release versions of the plugin.
#
# Workflow is triggered on pull requests to the repo.
#
# Additional Docs:
# - GitHub Actions: https://help.github.com/en/actions

name: build-pr
on:
  pull_request:
    paths-ignore:
      - '*.md'
jobs:

  # Build and test plugin and provide artifact.
  build:
    name: Build
    runs-on: codebuild-ion-intellij-plugin-${{ github.run_id }}-${{ github.run_attempt }}-arm-3.0-large
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
      - uses: gradle/actions/setup-gradle@v4

      # Build artifact using build Gradle task
      - name: Build
        run: ./gradlew build

      # Build artifact using buildPlugin Gradle task
      - name: Build Plugin
        run: ./gradlew buildPlugin

      # Run intellij:verifyPlugin task.
      - name: Verify Plugin
        run: ./gradlew verifyPlugin
