# GitHub Action Workflow for building a pull request commit and validating that the commit builds for all
# release versions of the plugin.
#
# Workflow is triggered on pull requests to the repo.
#
# Additional Docs:
# - GitHub Actions: https://help.github.com/en/actions

name: build-pr
on:
  pull_request:
    paths-ignore:
      - '*.md'
jobs:

  # Build and test plugin and provide artifact.
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      # Check out current repository
      - name: Fetch Sources
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - uses: gradle/actions/setup-gradle@v4
        with:
          cache-disabled: true

      # Build artifact using build Gradle task
      - name: Build
        run: ./gradlew build

      # Build artifact using buildPlugin Gradle task
      - name: Build Plugin
        run: ./gradlew buildPlugin

      - name: Get Product Versions
        id: get-products
        run: |
          PRODUCTS="$(./gradlew printProductsReleases -q | jq -cnR '[inputs | select(length > 0)]')"
          echo "products=$PRODUCTS"
          echo "products=$PRODUCTS" >> "$GITHUB_OUTPUT"

    outputs:
      products: ${{ steps.get-products.outputs.products }}

  verify:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      fail-fast: false
      matrix:
        product: ${{ fromJSON(needs.build.outputs.products) }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
      - uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: true

      # Run intellij:verifyPlugin task.
      - name: Verify Plugin
        run: ./gradlew verifyPlugin -PverifyPlugin="${{ matrix.product }}"
